export const data = [
  {
    question: "Which device is required for the Internet connection?",
    option1: "Modem",
    option2: "Router",
    option3: "LAN Cable",
    option4: "Pen Drive",
    ans: 1,
  },
  {
    question: "Which continent has the highest number of countries?",
    option1: "Asia",
    option2: "Europe",
    option3: "North America",
    option4: "Africa",
    ans: 4,
  },
  {
    question: "Junk e-mail is also called?",
    option1: "Spam",
    option2: "Fake",
    option3: "Archived",
    option4: "Bin",
    ans: 1,
  },
  {
    question: "A computer cannot BOOT if it does not have the?",
    option1: "Application Software",
    option2: "Internet",
    option3: "Operating System",
    option4: "Mouse",
    ans: 3,
  },
  {
    question: "First page of a Website is called?",
    option1: "Index Page",
    option2: "Homepage",
    option3: "Sitemap",
    option4: "Dashboard",
    ans: 2,
  },
  {
    question: "Which memory is known as volatile memory?",
    option1: "ROM",
    option2: "Hard Disk",
    option3: "RAM",
    option4: "Pendrive",
    ans: 3,
  },
  {
    question: "Which programming language is used for web development?",
    option1: "Python",
    option2: "JavaScript",
    option3: "C",
    option4: "Java",
    ans: 2,
  },
  {
    question: "What does CPU stand for?",
    option1: "Central Processing Unit",
    option2: "Central Printing Unit",
    option3: "Control Processing Unit",
    option4: "Compute Power Unit",
    ans: 1,
  },
  {
    question: "Which planet is known as the Red Planet?",
    option1: "Mars",
    option2: "Venus",
    option3: "Earth",
    option4: "Mercury",
    ans: 1,
  },
  {
    question: "Which gas do plants absorb from the atmosphere?",
    option1: "Oxygen",
    option2: "Carbon Dioxide",
    option3: "Nitrogen",
    option4: "Hydrogen",
    ans: 2,
  },
  {
    question: "What is the full form of ATM?",
    option1: "Automatic Transaction Machine",
    option2: "Automated Teller Machine",
    option3: "Automatic Transfer Machine",
    option4: "Account Teller Machine",
    ans: 2,
  },
  {
    question: "Which of the following is a web browser?",
    option1: "Google Chrome",
    option2: "MS Word",
    option3: "Excel",
    option4: "Photoshop",
    ans: 1,
  },
  {
    question: "Which country is the largest in the world by area?",
    option1: "China",
    option2: "USA",
    option3: "Russia",
    option4: "Canada",
    ans: 3,
  },
  {
    question: "What is H2O commonly known as?",
    option1: "Salt",
    option2: "Hydrogen",
    option3: "Oxygen",
    option4: "Water",
    ans: 4,
  },
  {
    question: "Which device is used to take a hard copy of a document?",
    option1: "Monitor",
    option2: "Printer",
    option3: "Scanner",
    option4: "Keyboard",
    ans: 2,
  },
  {
    question: "Which of the following is used for sending emails?",
    option1: "Gmail",
    option2: "PowerPoint",
    option3: "Excel",
    option4: "Photoshop",
    ans: 1,
  },
  {
    question: "Which element is essential for breathing?",
    option1: "Carbon",
    option2: "Oxygen",
    option3: "Nitrogen",
    option4: "Helium",
    ans: 2,
  },
  {
    question: "Which is the fastest land animal?",
    option1: "Lion",
    option2: "Tiger",
    option3: "Cheetah",
    option4: "Leopard",
    ans: 3,
  },
  {
    question: "Which company developed the Windows operating system?",
    option1: "Apple",
    option2: "Microsoft",
    option3: "Google",
    option4: "IBM",
    ans: 2,
  },
  {
    question: "What is the currency of Japan?",
    option1: "Yen",
    option2: "Dollar",
    option3: "Euro",
    option4: "Won",
    ans: 1,
  }
];
